[pytest]

testpaths =
    tests

python_files =
    test_*.py

addopts =
    -v
    --html=reports/report.html
    --self-contained-html

pythonpath = .

log_cli = true
log_cli_level = INFO

markers =
    auth: authentication tests
    booking: booking API tests